---
- hosts: slave2
  user: clckwrk
  become: true
  tasks:
    - name: "install dependencies"
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - wget
        - yum-utils
        - docker
    - name: "start docker service"
      service:
        name: docker
        state: started
        enabled: yes
  handlers:
    - name: "restart docker"
      service:
        name: docker
        state: restarted
---
- hosts: slave1
  user: centos
  become: true
  tasks:
    - name: "install dependencies"
      yum:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - yum-utils
        - podman
